{
 "title": "kube-router",
 "tags": [
  "Kubernetes",
  "kube-router",
  "networking"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "selnamespace",
    "label": "Namespace",
    "query": "label_values(kube_router_service_total_connections, svc_namespace)"
   },
   {
    "name": "selnode",
    "label": "Instance",
    "query": "label_values(kube_router_service_total_connections, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Time it took for controller to sync iptables",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_iptables_sync_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time it took for controller to sync ipvs services",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_ipvs_services_sync_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time it took for controller to sync policy chains",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_policy_chains_sync_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time it took to export metrics",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_ipvs_metrics_export_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time it took to sync internal bgp peers",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_bgp_internal_peers_sync_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time it took to sync internal bgp peers",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum by (le) (increase(kube_router_controller_routes_sync_time_bucket{instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps", "label": "Per second" }
   ],
   "targets": [
    {
     "expr": "sum(kube_router_service_pps_in{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "in {{svc_namespace}}/{{service_name}} {{port}}/{{protocol}}"
    },
    {
     "expr": "- sum(kube_router_service_pps_out{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "out {{svc_namespace}}/{{service_name}} {{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "Traffic by node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(kube_router_service_bps_in{instance=~\"[[selnode]]\"}) by (instance)",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "- sum(kube_router_service_bps_out{instance=~\"[[selnode]]\"}) by (instance)",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "Ipvs services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Per node" }
   ],
   "targets": [
    {
     "expr": "sum(kube_router_controller_ipvs_services{instance=~\"[[selnode]]\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BGP peers 5m avg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "\nsort_desc(sum(kube_router_controller_bgp_peers{instance=~\"[[selnode]]\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BGP announcements",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_router_controller_bgp_advertisements_received{instance=~\"[[selnode]]\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} received"
    },
    {
     "expr": "-sum(increase(kube_router_controller_bgp_advertisements_sent{instance=~\"[[selnode]]\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} sent"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_router_service_bytes_in{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}[$interval])) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(kube_router_service_bps_in{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "in {{svc_namespace}}/{{service_name}} {{port}}/{{protocol}}"
    },
    {
     "expr": "- sum(kube_router_service_bps_out{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "out {{svc_namespace}}/{{service_name}} {{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_router_service_bytes_out{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}[$interval])) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Packets In",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_router_service_packets_in{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}[$interval])) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Total connections made to the service",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum by (svc_namespace, service_name, port, protocol) (increase(kube_router_service_total_connections{svc_namespace=~\"$selnamespace\",instance=~\"$selnode\"}[$interval]))",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Packets Out",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_router_service_packets_out{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}[$interval])) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Connections per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_router_service_cps{svc_namespace=~\"[[selnamespace]]\",instance=~\"[[selnode]]\"}) by (svc_namespace, service_name, protocol, port)",
     "legendFormat": "{{svc_namespace}}/{{service_name}} {{port}}/{{protocol}}"
    }
   ]
  }
 ]
}