{
 "title": "Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 0 },
   "content": "<iframe src='https://10.31.0.201/admin/system/appmon-actual-status.php?lsm=1&nowarn=1' frameborder='0' scrolling='no' width=\"100%\" height=\"100%\">\n</iframe> "
  },
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 0 },
   "content": "<iframe src='https://10.31.0.201/monitor/domotiga.php' frameborder='0' scrolling='no' width=\"100%\" height=\"100%\">\n</iframe> "
  },
  {
   "title": "OPENNEBULA: VMs state",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count_values(\"state\", opennebula_vm_state)"
    }
   ]
  },
  {
   "title": "OPENNEBULA: CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "sum(opennebula_host_max_cpu)", "legendFormat": "Total CPU" },
    { "expr": "sum(opennebula_host_cpu_usage)", "legendFormat": "CPU usage " },
    { "expr": "sum(opennebula_host_used_cpu)", "legendFormat": "Used CPU" }
   ]
  },
  {
   "title": "OPENNEBULA: RAM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "expr": "sum(opennebula_host_total_mem)", "legendFormat": "Total memory" },
    { "expr": "sum(opennebula_host_mem_usage)", "legendFormat": "Memory usage" },
    { "expr": "sum(opennebula_host_used_mem)", "legendFormat": "Used memory" }
   ]
  },
  {
   "title": "OPENNEBULA: Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "opennebula_datastore_total_mb{name=\"cloud-images\",}",
     "legendFormat": "{{name}} Free space"
    },
    {
     "expr": "opennebula_datastore_used_mb{name=\"cloud-images\"}",
     "legendFormat": "{{name}} Used space"
    }
   ]
  },
  {
   "title": "LINSTOR: Device in wrong state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(linstor_resource_state{disk_state!=\"Diskless\",disk_state!=\"UpToDate\"})"
    }
   ]
  },
  {
   "title": "OPENNEBULA: VMs LCM state",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_values(\"state\", opennebula_vm_lcm_state)"
    }
   ]
  },
  {
   "title": "FTP check (problem hosts)",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 17 },
   "targets": [
    { "expr": "ftp_login!=230", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "OPENNEBULA: Hosts state",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count_values(\"state\", opennebula_host_state)"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})"
    }
   ]
  }
 ]
}